AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index_photo.lambda_handler
      Runtime: python3.8
      CodeUri: ./Backend/lambda1_index_photos.py
      FunctionName: “index_photo”
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: voice_lambda2.lambda_handler
      Runtime: python3.8
      CodeUri: ./Backend/lambda2_search_photos.py
      FunctionName: “voice_lambda2”